#ifndef APP_CONFIG_H
#define APP_CONFIG_H

// Enable necessary modules
#define NRFX_CLOCK_ENABLED 1
#define NRFX_CLOCK_CONFIG_LF_SRC 1

#define NRFX_PWM_ENABLED 1
#define NRFX_PWM0_ENABLED 1

#define NRFX_GPIOTE_ENABLED 1
#define NRFX_GPIOTE_CONFIG_NUM_OF_LOW_POWER_EVENTS 4

#define APP_TIMER_ENABLED 1
#define APP_TIMER_CONFIG_RTC_FREQUENCY 0
#define APP_TIMER_CONFIG_OP_QUEUE_SIZE 8
#define APP_TIMER_CONFIG_USE_SCHEDULER 0

#define NRF_LOG_ENABLED 1
#define NRF_LOG_BACKEND_UART_ENABLED 1
#define NRF_LOG_BACKEND_RTT_ENABLED 0
#define NRF_LOG_DEFAULT_LEVEL 4

#define NRF_SDH_BLE_ENABLED 0

#endif // APP_CONFIG_H
